written = [
    "asynchronous_search.rs",
    "cat.rs",
    "cluster.rs",
    "dangling_indices.rs",
    "flow_framework.rs",
    "geospatial.rs",
    "indices.rs",
    "ingest.rs",
    "ingestion.rs",
    "insights.rs",
    "ism.rs",
    "knn.rs",
    "list.rs",
    "ltr.rs",
    "ml.rs",
    "neural.rs",
    "nodes.rs",
    "notifications.rs",
    "observability.rs",
    "ppl.rs",
    "query.rs",
    "remote_store.rs",
    "replication.rs",
    "rollups.rs",
    "root/mod.rs",
    "search_pipeline.rs",
    "search_relevance.rs",
    "security.rs",
    "security_analytics.rs",
    "sm.rs",
    "snapshot.rs",
    "sql.rs",
    "tasks.rs",
    "transforms.rs",
    "ubi.rs",
    "wlm.rs",
]
merged = [
    "lib.rs",
    "params.rs",
]
