name: Setup Rust tools
description: Sets up Rust tools
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - name: Install latest stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy, llvm-tools-preview

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1

    - name: Cargo Cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          client
      
    - name: Determine grcov artifact
      id: determine-grcov-artifact
      shell: bash -eo pipefail {0}
      run: |
        case "$RUNNER_OS" in
          Linux)
            triple="unknown-linux-gnu"
            ext="tar.bz2"
            ;;
          macOS)
            triple="apple-darwin"
            ext="tar.bz2"
            ;;
          Windows)
            triple="pc-windows-msvc"
            ext="zip"
        esac
        echo "name=grcov-x86_64-${triple}.${ext}" >> $GITHUB_OUTPUT
      env:
        RUNNER_OS: ${{ runner.os }}

    - name: Download grcov
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mozilla/grcov
        latest: true
        fileName: ${{ steps.determine-grcov-artifact.outputs.name }}

    - name: Install grcov
      shell: bash -eo pipefail {0}
      run: |
        case "$FILE" in
          *.tar.bz2)
            tar -xjf $FILE
            ;;
          *.zip)
            unzip $FILE
            ;;
        esac

        rm -f $FILE
        mv ./grcov* ~/.cargo/bin/
        chmod +x ~/.cargo/bin/grcov
      env:
        FILE: ${{ steps.determine-grcov-artifact.outputs.name }}