name: Setup Rust tools
description: Sets up Rust tools
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - name: Install latest stable toolchain
      uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      with:
        components: rustfmt, clippy, llvm-tools-preview

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@d8952235ddd22b65d7c6b9194d4dbd58c3ffc48a

    - name: Cargo Cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
      with:
        workspaces: |
          client

    - name: Determine grcov artifact
      id: determine-grcov-artifact
      shell: bash -eo pipefail {0}
      run: |
        case "$RUNNER_OS" in
          Linux)
            triple="unknown-linux-gnu"
            ext="tar.bz2"
            ;;
          macOS)
            triple="apple-darwin"
            ext="tar.bz2"
            ;;
          Windows)
            triple="pc-windows-msvc"
            ext="zip"
        esac
        echo "name=grcov-x86_64-${triple}.${ext}" >> $GITHUB_OUTPUT
      env:
        RUNNER_OS: ${{ runner.os }}

    - name: Download grcov
      uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f
      with:
        repository: mozilla/grcov
        latest: true
        fileName: ${{ steps.determine-grcov-artifact.outputs.name }}

    - name: Install grcov
      shell: bash -eo pipefail {0}
      run: |
        case "$FILE" in
          *.tar.bz2)
            tar -xjf $FILE
            ;;
          *.zip)
            unzip $FILE
            ;;
        esac

        rm -f $FILE
        mv ./grcov* ~/.cargo/bin/
        chmod +x ~/.cargo/bin/grcov
      env:
        FILE: ${{ steps.determine-grcov-artifact.outputs.name }}
