name: Setup Rust tools
description: Sets up Rust tools
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - name: Install latest stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy, llvm-tools-preview

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1

    - name: Cargo Cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          client
      
    - name: Download grcov
      uses: robinraju/release-downloader@v1.7
      with:
        repository: mozilla/grcov
        latest: true
        fileName: 'grcov-x86_64-unknown-linux-gnu.tar.bz2'

    - name: Install grcov
      shell: bash
      run: |
        tar -xjf grcov-x86_64-unknown-linux-gnu.tar.bz2 \
        && rm -f grcov-*.tar.bz2 \
        && mv ./grcov ~/.cargo/bin/ \
        && chmod +x ~/.cargo/bin/grcov