#!/usr/bin/env bash
#
# Version 1.1
# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products

export CLUSTER="${1:=opensearch}"
export STACK_VERSION="${2:-latest}"
export SECURE_INTEGRATION="${3:-false}"

if [[ "$SECURE_INTEGRATION" == "true" ]]; then
  export DISABLE_SECURITY="false"
else
  export DISABLE_SECURITY="true"
fi

script_path=$(dirname $(realpath -s $0))
source $script_path/functions/imports.sh
set -euo pipefail

DETACH=true bash .ci/run-opensearch.sh

if [[ -n "$RUNSCRIPTS" ]]; then
  for RUNSCRIPT in ${RUNSCRIPTS//,/ } ; do
    echo -e "\033[1m>>>>> Running run-$RUNSCRIPT.sh >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
    CONTAINER_NAME=${RUNSCRIPT} \
      DETACH=true \
      bash .ci/run-${RUNSCRIPT}.sh
  done
fi

echo -e "\033[1m>>>>> Repository specific tests >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
bash .ci/run-repository.sh