name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Backport
        uses: VachaShah/backport@v1.1.4
        with:
          github_token: ${{ steps.github_app_token.outputs.token }}
          branch_name: backport/backport-${{ github.event.number }}
